---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    user: ctt
    gps_pin: 27
  roles:
    - init
    - bob-dev
    - hwclock
    - gps
    - enable-pps
    - enable-modem
    - handle-uart
    - chrony
    - crypto-chip
