---
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - init
    - bob-dev
    - hwclock
    - gps
    - enable-pps
    - enable-modem
    - handle-uart
    - chrony
    - install-node-npm
    - crypto-chip
    - install-ctt-software
    - configure-ctt-software
    - wrap-up
    