---
- name: ensure /lib/ctt directory exists
  become: yes
  ansible.builtin.file:
    path: "{{ software_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: create ctt virtual environment directory
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.file:
    path: "{{ software_dir }}/.envs"
    state: directory

- name: create python virutal environment for the sensor station
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.shell: python3 -m venv "{{ software_dir }}/.envs/station"

- name: pip install dependencies
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.pip:
    name:
      - boto3
      - requests
      - pytz
    virtualenv: "{{ software_dir }}/.envs/station"

- name: git ctt station software
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: https://github.com/cellular-tracking-technologies/sensor-station-software.git
    dest: "{{ software_dir }}/sensor-station-software"

- name: install sensor-station-software node modules
  become: yes
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: npm install --python=python2.7
    chdir: "{{ software_dir }}/sensor-station-software"

- name: ensure bootcount file exists for hardware server check
  become: yes
  ansible.builtin.copy:
    dest: '/etc/bootcount'
    content: '0'
