---
- name: git station-utils
  become: yes
  become_user: pi
  git:
    repo:  https://github.com/cellular-tracking-technologies/station-utils.git
    dest: "{{ software_dir }}/station-utils"
    force: yes

- name: create ctt virtual environment directory
  become: yes
  become_user: pi
  file:
    path: /home/pi/ctt/.envs
    state: directory

- name: create python virutal environment for the sensor station
  become: yes
  become_user: pi
  shell: python3 -m venv /home/pi/ctt/.envs/station

- name: pip install dependencies
  become: yes
  become_user: pi
  pip:
    name:
      - boto3
      - requests
      - pytz
    virtualenv: /home/pi/ctt/.envs/station

- name: copy upload script
  become: yes
  copy:
    src: "files/upload-station-data.sh"
    dest: "/usr/bin/upload-station-data"
    mode: "0755"

- name: copy station-update script
  become: yes
  copy:
    src: "files/bash-update-station.sh"
    dest: "/usr/bin/bash-update-station"
    mode: "0755"

- name: upload cron job
  become: yes
  cron:
    name: "data upload cron job"
    minute: 11
    job: "upload-station-data"

- name: bash update cron job
  become: yes
  cron:
    name: "bash update station OTA"
    hour: 20
    minute: 43 
    job: "bash-update-station"

- name: reboot weekly
  become: yes
  cron:
    name: "reboot weekly"
    hour: 06
    minute: 43
    day: 3
    job: "/sbin/shutdown -r now"

- name: git station-hardware-server
  become: yes
  become_user: pi
  git:
    repo:  https://github.com/cellular-tracking-technologies/station-hardware-server.git
    dest: "{{ software_dir }}/station-hardware-server"
    force: yes

- name: install station-hardware-server
  become: yes
  become_user: pi
  shell:
    cmd: npm install
    chdir: "{{ software_dir }}/station-hardware-server"

- name: compile station-hardware-server
  become: yes
  become_user: pi
  shell:
    cmd: npm run build
    chdir: "{{ software_dir }}/station-hardware-server"

- name: git station-lcd-interface
  become: yes
  become_user: pi
  git:
    repo:  https://github.com/cellular-tracking-technologies/station-lcd-interface.git
    dest: "{{ software_dir }}/station-lcd-interface"
    force: yes

- name: install station-lcd-interface
  become: yes
  become_user: pi
  shell:
    cmd: npm install
    chdir: "{{ software_dir }}/station-lcd-interface"

- name: compile station-lcd-interface
  become: yes
  become_user: pi
  shell:
    cmd: npm run build
    chdir: "{{ software_dir }}/station-lcd-interface"

- name: git station radio interface
  become: yes
  become_user: pi
  git:
    repo: https://github.com/cellular-tracking-technologies/station-radio-interface.git
    dest: "{{ software_dir }}/station-radio-interface"
    force: yes
    version: v2

- name: install station-radio-interface
  become: yes
  become_user: pi
  shell:
    cmd: npm install
    chdir: "{{ software_dir }}/station-radio-interface"

- name: compile station-radio-interface
  become: yes
  become_user: pi
  shell:
    cmd: npm run build
    chdir: "{{ software_dir }}/station-radio-interface"

- name: git station interface
  become: yes
  become_user: pi
  git:
    repo: https://github.com/cellular-tracking-technologies/station-interface.git
    dest: "{{ software_dir }}/station-interface"
    force: yes
    version: v2

- name: install station-interface
  become: yes
  become_user: pi
  shell:
    cmd: npm install
    chdir: "{{ software_dir }}/station-interface"

- name: compile station-interface
  become: yes
  become_user: pi
  shell:
    cmd: npm run prep && npm run build
    chdir: "{{ software_dir }}/station-interface"
