---
- name: create ctt virtual environment directory
  become: yes
  become_user: ctt
  file:
    path: /home/ctt/ctt/.envs
    state: directory

- name: create python virutal environment for the sensor station
  become: yes
  become_user: ctt
  shell: python3 -m venv /home/ctt/ctt/.envs/station

- name: pip install dependencies
  become: yes
  become_user: ctt
  pip:
    name:
      - boto3
      - requests
      - pytz
    virtualenv: /home/ctt/ctt/.envs/station

- name: git ctt station software
  become: yes
  become_user: ctt
  git:
    repo: https://github.com/cellular-tracking-technologies/sensor-station-software.git
    dest: "{{ software_dir }}//sensor-station-software"

- name: install sensor-station-software node modules
  become: yes
  become_user: ctt
  shell:
    cmd: npm install
    chdir: "{{ software_dir }}/sensor-station-software"
