---
- name: make sure /etc/ctt exists
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  with_items:
    - { path: '/etc/ctt/scripts'}
    - { path: '/data' }
    - { path: '/etc/ctt/fw' }

- name: copy configuration scripts
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'station-id.sh', dest: '/usr/bin/station-id', mode: '0755' }
    - { src: 'save-station-id.sh', dest: '/etc/ctt/scripts/save-station-id.sh', mode: '0755' }
    - { src: 'files/station-boot.service', dest: '/etc/systemd/system', mode: '0400' }
    - { src: 'files/program-radios.sh', dest: '/usr/bin/program-radios', mode: '0755' }
    - { src: 'files/program-radio.sh', dest: '/usr/bin/program-radio', mode: '0755' }
    - { src: 'files/update-station.sh', dest: '/usr/bin/update-station', mode: '0755' }
    - { src: 'files/ss_v2.4.1.hex', dest: '/etc/ctt/fw', mode: '0400' }

- name: default fw link
  become: yes
  file:
      src: /etc/ctt/fw/ss_v2.4.1.hex
      dest: /etc/ctt/fw/default
      state: link

- name: enable station id on boot
  become: yes
  systemd:
    daemon_reload: yes
    name: station-boot.service
    state: started
    enabled: yes
 
- name: install pm2 ecosystem
  become: yes
  copy:
    src: "ecosystem.config.js"
    dest: "/etc/ctt/ecosystem.config.js"
    mode: '0400'

- name: start pm2
  become: yes
  shell:
    cmd: "pm2 start /etc/ctt/ecosystem.config.js"

- name: enable pm2 startup
  become: yes
  shell:
    cmd: "pm2 startup"

- name: persist startup
  become: yes
  shell:
    cmd: "pm2 save"

- name: pm2 log rotate
  become: yes
  shell:
    cmd: "pm2 install pm2-logrotate"

- name: pm2 compress rotated logs
  become: yes
  shell:
    cmd: "pm2 set pm2-logrotate:compress true"

- name: pm2 maintain 180 days of logs
  become: yes
  shell:
    cmd: "pm2 set pm2-logrotate:retain 180"