---
- name: make sure /etc/ctt directories /data directory exists
  become: yes
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  with_items:
    - { path: '/etc/ctt/fw' }
    - { path: '/data' }

- name: copy radio firmware
  become: yes
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "files/fw/ss_v2.4.1.hex", dest: '/etc/ctt/fw/ss_v2.4.1.hex' }
    - { src: "files/fw/ss_v3.0.0.hex", dest: '/etc/ctt/fw/ss_v3.0.0.hex' }

- name: create symlinks
  become: yes
  ansible.builtin.file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
      force: yes
  with_items:
    - { src: "{{ software_dir }}/sensor-station-software/system/scripts/station-id.sh", dest: '/usr/local/sbin/station-id'}
    - { src: "{{ software_dir }}/sensor-station-software/system/scripts/program-radios.sh", dest: '/usr/local/sbin/program-radios'}
    - { src: "{{ software_dir }}/sensor-station-software/system/scripts/program-radio.sh", dest: '/usr/local/sbin/program-radio'}
    - { src: "{{ software_dir }}/sensor-station-software/system/scripts/update-station.sh", dest: '/usr/local/sbin/update-station'}
    - { src: "{{ software_dir }}/sensor-station-software/system/scripts/bash-update-station.sh", dest: '/usr/local/sbin/bash-update-station'}
    - { src: "{{ software_dir }}/sensor-station-software/system/scripts/upload-station-data.sh", dest: '/usr/local/sbin/upload-station-data'}
    - { src: "{{ software_dir }}/sensor-station-software/system/systemd/station-boot.service", dest: '/etc/systemd/system/station-boot.service' }
    - { src: "{{ software_dir }}/sensor-station-software/system/systemd/station-hardware-server.service", dest: '/etc/systemd/system/station-hardware-server.service' }
    - { src: "{{ software_dir }}/sensor-station-software/system/systemd/station-lcd-interface.service", dest: '/etc/systemd/system/station-lcd-interface.service' }
    - { src: "{{ software_dir }}/sensor-station-software/system/systemd/station-radio-interface.service", dest: '/etc/systemd/system/station-radio-interface.service' }
    - { src: "{{ software_dir }}/sensor-station-software/system/systemd/station-web-interface.service", dest: '/etc/systemd/system/station-web-interface.service' }
    - { src: "/etc/ctt/fw/ss_v3.0.0.hex", dest: "/etc/ctt/fw/default" }

- name: enable ctt services on boot
  become: yes
  ansible.builtin.systemd:
    name:  "{{ item.name }}"
    state: started
    enabled: yes
  with_items:
    - { name: 'station-boot.service' }
    - { name: 'station-hardware-server.service' }
    - { name: 'station-radio-interface.service' }
    - { name: 'station-lcd-interface.service' }
    - { name: 'station-web-interface.service' }
 
- name: reload systemd
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: upload cron job
  become: yes
  ansible.builtin.cron:
    name: "data upload cron job"
    minute: 11
    job: "/usr/local/sbin/upload-station-data"

- name: bash update cron job
  become: yes
  ansible.builtin.cron:
    name: "bash update station OTA"
    hour: 20
    minute: 43 
    job: "/usr/local/sbin/bash-update-station"

- name: reboot weekly
  become: yes
  ansible.builtin.cron:
    name: "reboot weekly"
    hour: 06
    minute: 43
    day: 3
    job: "/sbin/shutdown -r now"