- name: install chrony 
  become: yes
  ansible.builtin.apt: 
    name: chrony
    state: latest

- name: create chrony conf link
  become: yes
  ansible.builtin.file:
    src: "{{ software_dir }}/sensor-station-software/system/chrony/ctt-chrony.conf"
    dest: /etc/chrony/chrony.conf
    state: link
    force: yes

- name: restart chrony
  become: yes
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
    enabled: yes
    daemon_reload: yes