---
- name: install gps software
  become: true
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: latest 
  vars:
    packages:
    - gpsd
    - gpsd-clients

- name: configure gpsd
  become: true
  ansible.builtin.file:
    src: "{{ software_dir }}/sensor-station-software/system/gps/ctt-gpsd.conf"
    dest: /etc/default/gpsd
    state: link
    force: yes

# enable gpsd service on start
- name: enable gpsd systemd
  become: true
  ansible.builtin.systemd:
    name: gpsd
    enabled: true

- name: enusure pps-gpio module is loaded at boot
  become: true
  ansible.builtin.lineinfile:
    backup: true
    path: /etc/modules
    line: pps-gpio
