---
- name: update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

# station hardware configuration 
- name: copy boot/config.txt
  become: yes
  copy:
    src: files/config.txt
    dest: /boot/config.txt

# disable auto upgrades...
- name: disable auto upgrades / daily upgrades...
  become: yes
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.masked }}"
    masked: "{{ item.enabled }}"
  with_items:
    - { name: 'apt-daily-upgrade', masked: yes, enabled: no }
    - { name: 'apt-daily', masked: yes, enabled: no }
    - { name: 'apt-daily-upgrade.timer', masked: no, enabled: no }
    - { name: 'apt-daily.timer', masked: no, enabled: no }

- name: reboot before removing unattended upgrades...
  become: yes
  reboot:

# remove unattended upgrades...
- name: remove unattended upgrades
  become: yes
  ansible.builtin.apt:
    name: unattended-upgrades
    state: absent
    purge: yes

- name: ensure /etc/ctt exists
  become: yes
  file:
    path: /etc/ctt
    state: directory
    mode: '0755'

- name: create station image file
  become: yes
  shell: date -I > /etc/ctt/station-image

- name: create station software file
  become: yes
  shell: date -I > /etc/ctt/station-software

- name: copy station hosts on boot
  become: yes
  template:
    src: files/hosts
    dest: /etc/hosts

- name: copy hostname
  become: yes
  copy:
    content: "{{hostname}}"
    dest: /etc/hostname

- name: install system packages
  become: true
  apt: 
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - git
    - build-essential
    - software-properties-common
    - minicom # for serial debugging
    - raspi-gpio # GPIO command line utility
    - i2c-tools
    - libudev-dev
    - cmake
    - python3-pip
    - python-dev
    - python3-wheel
    - python3-smbus
    - python3-venv
    - exfat-fuse
    - exfat-utils
    - avrdude
    - bmon

- name: enable i2c access
  become: true
  lineinfile:
    path: /etc/modules
    line: i2c-dev

- name: set timezone
  become: yes
  shell:
    cmd: timedatectl set-timezone America/New_York