---
- name: install ppp
  become: yes
  apt:
    name: ppp
    state: latest

- name: create modem rules folder
  become: yes
  file:
    path: /etc/ctt/modem
    state: directory
    mode: '0755'

- name: copy configuration scripts
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'files/twilio-chatscript', dest: '/etc/chatscripts/twilio'}
    - { src: 'files/simcom-chat-disconnect', dest: '/etc/chatscripts/disconnect'}
    - { src: 'files/ppp-gprs', dest: '/etc/ppp/peers/gprs' }
    - { src: 'files/modem.service', dest: '/etc/systemd/system'}
    - { src: 'files/quectel-modem.rules', dest: '/etc/ctt/modem/quectel-modem.rules' }

- name: create link to default quectel modem
  become: yes
  file:
    src: /etc/ctt/modem/quectel-modem.rules
    dest: /etc/udev/rules.d/23-modem.rules
    state: link

- name: reload systemd
  become: yes
  systemd:
    daemon_reload: yes

- name: enable modem conn on boot
  become: yes
  systemd:
    name: modem.service
    state: started
    enabled: yes

