---
- name: install ppp
  become: yes
  ansible.builtin.apt:
    name: ppp
    state: latest

- name: create modem rules folder
  become: yes
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  with_items:
    - { path: '/etc/ctt/fw' }
    - { path: '/etc/ctt/modem' }
    - { path: '/etc/ctt/radios' }
    - { path: '/etc/ctt/scripts' }
    - { path: '/etc/ctt/systemd' }

- name: link to chatscripts / modem service / modem udev rules
  become: yes
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - { src: "{{ software_dir }}/sensor-station-software/system/modem/twilio-chatscript", dest: '/etc/chatscripts/twilio'}
    - { src: "{{ software_dir }}/sensor-station-software/system/modem/simcom-chat-disconnect", dest: '/etc/chatscripts/disconnect'}
    - { src: "{{ software_dir }}/sensor-station-software/sytem/modem/ppp-gprs", dest: '/etc/ppp/peers/gprs' }
    - { src: "{{ software_dir }}/sensor-station-software/system/modem/modem.service", dest: '/etc/systemd/system/modem.service'}
    - { src: "{{ software_dir }}/sensor-station-software/system/modem/quectel-modem.rules", dest: '/etc/udev/rules.d/23-modem.rules' }

- name: reload systemd
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: enable modem conn on boot
  become: yes
  ansible.builtin.systemd:
    name: modem.service
    state: started
    enabled: yes

- name: deny wwan0 interface
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/dhcpcd.conf
    regexp: 'denyinterfaces wwan0'
    line: 'denyinterfaces wwan0'